# Generated by Django 5.0.7 on 2024-08-01 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=60, verbose_name='Titulo')),
                ('event_type', models.CharField(choices=[('Show', 'Show'), ('Apresentação Teatral', 'Apresentação Teatral'), ('Orquestra', 'Orquestra'), ('Musical', 'Musical'), ('Show de comedia', 'Show de comedia'), ('Outro', 'Outro')], verbose_name='Tipo de evento')),
                ('event_start_date', models.DateTimeField(verbose_name='Data de Inicio')),
                ('event_end_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de Termino')),
                ('event_time', models.TimeField(verbose_name='Horario do evento')),
                ('event_location', models.CharField(verbose_name='Endereço do evento')),
                ('event_location_city', models.CharField(verbose_name='Cidade do evento')),
                ('event_is_free', models.BooleanField(default=False)),
                ('event_voucher_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Preço do Ingresso')),
                ('event_vacancies', models.IntegerField(blank=True, null=True, verbose_name='Vagas')),
            ],
        ),
    ]
