# Generated by Django 5.0.7 on 2024-08-03 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='event_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Termino'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='event_start_date',
            field=models.DateField(verbose_name='Data de Inicio'),
        ),
    ]
