# Generated by Django 5.0.7 on 2024-08-08 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0002_alter_activity_event_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='event_is_limitles_vacancies',
            field=models.BooleanField(default=False),
        ),
    ]
