# Generated by Django 5.0.7 on 2024-08-08 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0003_activity_event_is_limitles_vacancies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='event_is_limitles_vacancies',
        ),
        migrations.AddField(
            model_name='activity',
            name='event_is_limitless_vacancies',
            field=models.BooleanField(default=False, verbose_name='Vagas ilimitadas'),
        ),
    ]
