# Generated by Django 5.0.7 on 2024-08-09 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0004_remove_activity_event_is_limitles_vacancies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='event_is_free',
            field=models.BooleanField(default=False, verbose_name='Eentrada gratuita'),
        ),
    ]
