# Generated by Django 5.0.7 on 2024-08-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0005_alter_activity_event_is_free'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='event_is_free',
            field=models.BooleanField(default=False, verbose_name='Entrada gratuita'),
        ),
    ]
